### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by luicap** [adithya321/Companion-for-Band#9]
Build version: 2.6.1 
Build date: 2016-05-12 20:41:56 
Current date: 2016-05-14 13:40:09 
Device: LGE LG-D320 

Stack trace:  
java.lang.IllegalStateException: Fragment SensorsFragment{42c8dd10} not attached to Activity
    at android.support.v4.app.Fragment.getResources(Fragment.java:636)
    at android.support.v4.app.Fragment.getString(Fragment.java:658)
    at com.pimp.companionforband.SensorsFragment$10.onBandHeartRateChanged(SensorsFragment.java:554)
    at com.microsoft.band.e.a(SourceFile:1068)
    at com.microsoft.band.f.a(SourceFile:7762)
    at com.microsoft.band.f$b.a(SourceFile:909)
    at com.microsoft.band.internal.d$3.handleMessage(SourceFile:136)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at com.microsoft.band.internal.d.run(SourceFile:147)

Debug info:
 OS Version: 3.4.0+(1415114669)
 OS API Level: 19
 Device: w5n
 Model (and Product): LG-D320 (w5n_global_com)
 RELEASE: 4.4.2
 BRAND: lge
 DISPLAY: KOT49I.A1415114669
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: w5n
 MANUFACTURER: LGE

Extra Info: Nothing to show.

**Comment by adithya321** [comment]
After what steps did this crash happen?
